// Level layouts - each layout is a 2D array where:
// false = no brick, true = normal brick, 2 = indestructible brick (from level 10+)
// Returns the number of hits required for a brick at this position and level
export const getBrickHits = (level: number, row: number): number => {
  if (level < 3) return 1;
  if (level < 5) return row < 2 ? 2 : 1;
  if (level < 8) return row < 3 ? 2 : 1;
  if (level < 12) return row < 2 ? 3 : row < 4 ? 2 : 1;
  if (level < 18) return row < 3 ? 3 : row < 5 ? 2 : 1;
  if (level < 25) return row < 2 ? 4 : row < 4 ? 3 : row < 6 ? 2 : 1;
  if (level < 35) return row < 3 ? 4 : row < 5 ? 3 : row < 7 ? 2 : 1;
  if (level < 45) return row < 2 ? 5 : row < 4 ? 4 : row < 6 ? 3 : row < 8 ? 2 : 1;
  return row < 3 ? 6 : row < 5 ? 5 : row < 7 ? 4 : row < 9 ? 3 : row < 11 ? 2 : 1;
};

export const levelLayouts: (boolean | number)[][][] = [
  // Level 1
  [
    [false, false, true, true, true, true, true, true, true, true, true, true, false, false],
    [false, true, true, true, true, true, true, true, true, true, true, true, true, false],
    [false, true, true, true, false, false, true, true, false, false, true, true, true, false],
    [false, true, true, true, false, false, true, true, false, false, true, true, true, false],
    [false, true, true, true, true, true, true, true, true, true, true, true, true, false],
    [false, true, true, true, true, true, true, true, true, true, true, true, true, false],
    [false, true, true, true, true, true, true, true, true, true, true, true, true, false],
    [false, true, false, false, false, false, false, false, false, false, false, false, true, false],
    [false, true, false, true, true, false, true, true, false, true, true, false, true, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false],
  ],

  // Level 2
  [
    [false, false, false, false, false, false, true, true, false, false, false, false, false, false],
    [false, false, false, false, false, true, true, true, true, false, false, false, false, false],
    [false, false, false, false, true, true, false, false, true, true, false, false, false, false],
    [false, false, false, true, true, false, true, true, false, true, true, false, false, false],
    [false, false, true, true, false, true, true, true, true, false, true, true, false, false],
    [false, true, true, false, true, true, false, false, true, true, false, true, true, false],
    [true, true, false, true, true, false, true, true, false, true, true, false, true, true],
    [true, false, true, true, false, true, true, true, true, false, true, true, false, true],
    [false, true, true, false, true, true, true, true, true, true, false, true, true, false],
    [true, true, false, true, true, true, true, true, true, true, true, false, true, true],
    [false, true, true, true, true, true, true, true, true, true, true, true, true, false],
    [false, false, true, true, true, true, true, true, true, true, true, true, false, false],
    [false, false, false, true, true, true, false, false, true, true, true, false, false, false],
    [false, false, false, false, true, false, false, false, false, true, false, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false],
  ],

  // Level 3
  [
    [false, false, false, true, true, true, false, false, true, true, true, false, false, false],
    [false, false, true, false, false, false, true, true, false, false, false, true, false, false],
    [false, true, false, true, true, true, false, false, true, true, true, false, true, false],
    [true, false, true, true, true, true, true, true, true, true, true, true, false, true],
    [true, false, true, true, true, true, true, true, true, true, true, true, false, true],
    [true, false, true, true, true, true, true, true, true, true, true, true, false, true],
    [false, true, false, true, true, true, true, true, true, true, true, false, true, false],
    [false, false, true, false, true, true, true, true, true, true, false, true, false, false],
    [false, false, false, true, false, true, true, true, true, false, true, false, false, false],
    [false, false, false, false, true, false, true, true, false, true, false, false, false, false],
    [false, false, false, false, false, true, false, false, true, false, false, false, false, false],
    [false, false, false, false, false, false, true, true, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false],
  ],

  // Level 4
  [
    [false, false, false, false, false, true, true, true, true, false, false, false, false, false],
    [false, true, false, false, true, false, false, false, false, true, false, false, true, false],
    [false, false, true, true, false, false, true, true, false, false, true, true, false, false],
    [false, false, false, false, true, false, true, true, false, true, false, false, false, false],
    [false, false, false, false, false, true, false, false, true, false, false, false, false, false],
    [false, false, false, true, true, true, false, false, true, true, true, false, false, false],
    [false, false, true, true, true, true, true, true, true, true, true, true, false, false],
    [false, false, false, false, true, false, false, false, false, true, false, false, false, false],
    [false, false, false, true, false, true, false, false, true, false, true, false, false, false],
    [false, true, true, true, false, true, true, true, true, false, true, true, true, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false],
  ],

  // Level 5
  [
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [false, true, true, true, true, false, false, false, false, true, true, true, true, false],
    [false, true, true, false, false, false, true, true, false, false, false, true, true, false],
    [false, false, false, false, false, true, true, true, true, false, false, false, false, false],
    [false, false, false, false, true, true, true, true, true, true, false, false, false, false],
    [false, false, false, true, true, true, true, true, true, true, true, false, false, false],
    [false, false, true, false, true, false, true, true, false, true, false, true, false, false],
    [false, true, false, true, false, true, false, false, true, false, true, false, true, false],
    [false, true, true, true, true, true, true, true, true, true, true, true, true, false],
    [false, false, false, false, true, false, false, false, false, true, false, false, false, false],
    [false, false, true, true, false, true, true, true, true, false, true, true, false, false],
    [false, true, true, true, false, true, false, false, true, false, true, true, true, false],
    [false, false, false, true, 2, 2, false, false, 2, 2, true, false, false, false],
    [false, false, true, false, false, false, false, false, false, false, false, true, false, false],
    [false, true, false, false, false, false, false, false, false, false, false, false, true, false],
    [false, false, true, false, false, false, false, false, false, false, false, true, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false],
  ],

  // Level 6: Checkerboard
  [
    [true, false, true, false, true, false, true, false, true, false, true, false, true, false],
    [false, true, false, true, false, true, false, true, false, true, false, true, false, true],
    [true, false, true, false, true, false, true, false, true, false, true, false, true, false],
    [false, true, false, true, false, true, false, true, false, true, false, true, false, true],
    [true, false, true, false, true, false, true, false, true, false, true, false, true, false],
    [false, true, false, true, false, true, false, true, false, true, false, true, false, true],
    [true, false, true, false, true, false, true, false, true, false, true, false, true, false],
    [false, true, false, true, false, true, false, true, false, true, false, true, false, true],
    [true, false, true, false, true, false, true, false, true, false, true, false, true, false],
    [false, true, false, true, false, true, false, true, false, true, false, true, false, true],
    [true, false, true, false, true, false, true, false, true, false, true, false, true, false],
    [false, true, false, true, false, true, false, true, false, true, false, true, false, true],
    [true, false, true, false, true, false, true, false, true, false, true, false, true, false],
    [false, true, false, true, false, true, false, true, false, true, false, true, false, true],
    [true, false, true, false, true, false, true, false, true, false, true, false, true, false],
    [false, true, false, true, false, true, false, true, false, true, false, true, false, true],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false],
  ],

  // Level 7: X Pattern
  [
    [true, true, false, false, false, false, false, false, false, false, false, false, true, true],
    [true, true, true, false, false, false, false, false, false, false, false, true, true, true],
    [false, true, true, true, false, false, false, false, false, false, true, true, true, false],
    [false, false, true, true, true, false, false, false, false, true, true, true, false, false],
    [false, false, false, true, true, true, false, false, true, true, true, false, false, false],
    [false, false, false, false, true, true, true, true, true, true, false, false, false, false],
    [false, false, false, false, false, true, true, true, true, false, false, false, false, false],
    [false, false, false, false, false, false, true, true, false, false, false, false, false, false],
    [false, false, false, false, false, false, true, true, false, false, false, false, false, false],
    [false, false, false, false, false, true, true, true, true, false, false, false, false, false],
    [false, false, false, false, true, true, true, true, true, true, false, false, false, false],
    [false, false, false, true, true, true, false, false, true, true, true, false, false, false],
    [false, false, true, true, true, false, false, false, false, true, true, true, false, false],
    [false, true, true, true, false, false, false, false, false, false, true, true, true, false],
    [true, true, true, false, false, false, false, false, false, false, false, true, true, true],
    [true, true, false, false, false, false, false, false, false, false, false, false, true, true],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false],
  ],

  // Level 8: Dense Grid
  [
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false],
  ],

  // Level 9: Full Grid
  [
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
  ],

  // Level 10: Indestructible Frame
  [
    [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
    [2, true, true, true, true, true, true, true, true, true, true, true, true, 2],
    [2, true, true, true, true, true, true, true, true, true, true, true, true, 2],
    [2, true, true, true, true, true, true, true, true, true, true, true, true, 2],
    [2, true, true, true, true, true, true, true, true, true, true, true, true, 2],
    [2, 2, 2, true, true, true, true, true, true, true, true, 2, 2, 2],
    [false, false, 2, true, true, true, true, true, true, true, true, 2, false, false],
    [false, false, 2, true, true, true, true, true, true, true, true, 2, false, false],
    [false, false, 2, true, true, true, true, true, true, true, true, 2, false, false],
    [false, false, 2, true, true, true, true, true, true, true, true, 2, false, false],
    [false, false, 2, true, true, true, true, true, true, true, true, 2, false, false],
    [false, false, 2, true, true, true, true, true, true, true, true, 2, false, false],
    [2, 2, 2, true, true, true, true, true, true, true, true, 2, 2, 2],
    [2, true, true, true, true, true, true, true, true, true, true, true, true, 2],
    [2, true, true, true, true, true, true, true, true, true, true, true, true, 2],
    [2, true, true, true, true, true, true, true, true, true, true, true, true, 2],
    [2, true, true, true, true, true, true, true, true, true, true, true, true, 2],
    [2, 2, 2, true, true, true, true, true, true, true, true, 2, 2, 2],
  ],

  // Level 11: Star Pattern
  [
    [false, false, false, false, false, false, true, true, false, false, false, false, false, false],
    [false, false, false, false, false, true, true, true, true, false, false, false, false, false],
    [false, false, false, false, true, true, true, true, true, true, false, false, false, false],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [false, false, true, true, true, true, true, true, true, true, true, true, false, false],
    [false, false, false, true, true, true, true, true, true, true, true, false, false, false],
    [false, false, true, true, true, false, true, true, false, true, true, true, false, false],
    [false, true, true, true, false, false, true, true, false, false, true, true, true, false],
    [true, true, true, false, false, false, true, true, false, false, false, true, true, true],
    [true, true, false, false, false, false, true, true, false, false, false, false, true, true],
    [true, false, false, false, false, false, false, false, false, false, false, false, false, true],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false],
  ],

  // Level 12: Arrow Down
  [
    [2, 2, 2, 2, true, true, true, true, true, true, 2, 2, 2, 2],
    [2, 2, 2, 2, true, true, true, true, true, true, 2, 2, 2, 2],
    [2, 2, 2, 2, true, true, true, true, true, true, 2, 2, 2, 2],
    [2, 2, 2, 2, true, true, true, true, true, true, 2, 2, 2, 2],
    [2, 2, 2, 2, true, true, true, true, true, true, 2, 2, 2, 2],
    [2, 2, 2, 2, true, true, true, true, true, true, 2, 2, 2, 2],
    [2, 2, 2, 2, true, true, true, true, true, true, 2, 2, 2, 2],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [false, true, true, true, true, true, true, true, true, true, true, true, true, false],
    [false, false, true, true, true, true, true, true, true, true, true, true, false, false],
    [false, false, false, true, true, true, true, true, true, true, true, false, false, false],
    [false, false, false, false, true, true, true, true, true, true, false, false, false, false],
    [false, false, false, false, false, true, true, true, true, false, false, false, false, false],
    [false, false, false, false, false, false, true, true, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false],
  ],

  // Level 13: Maze Pattern
  [
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [2, true, true, true, true, 2, true, true, true, true, true, true, true, 2],
    [2, true, 2, 2, true, 2, true, 2, 2, 2, 2, 2, true, 2],
    [2, true, 2, true, true, true, true, true, true, true, true, 2, true, 2],
    [2, true, 2, true, 2, 2, 2, 2, true, 2, true, 2, true, 2],
    [2, true, true, true, 2, true, true, true, true, 2, true, true, true, 2],
    [2, 2, 2, 2, 2, true, 2, 2, 2, 2, 2, 2, 2, 2],
    [2, true, true, true, true, true, 2, true, true, true, true, true, true, 2],
    [2, true, 2, 2, 2, 2, 2, true, 2, 2, 2, 2, true, 2],
    [2, true, true, true, true, true, true, true, true, true, true, 2, true, 2],
    [2, 2, 2, 2, 2, 2, true, 2, 2, 2, true, 2, true, 2],
    [2, true, true, true, true, 2, true, 2, true, true, true, 2, true, 2],
    [2, true, 2, 2, true, 2, true, 2, true, 2, 2, 2, true, 2],
    [2, true, true, true, true, true, true, true, true, true, true, true, true, 2],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false],
  ],

  // Level 14: Circles
  [
    [false, false, true, true, true, true, true, true, true, true, true, true, false, false],
    [false, true, true, true, true, true, true, true, true, true, true, true, true, false],
    [true, true, true, true, false, false, false, false, false, false, true, true, true, true],
    [true, true, true, false, false, false, false, false, false, false, false, true, true, true],
    [true, true, false, false, false, false, false, false, false, false, false, false, true, true],
    [true, true, false, false, false, false, false, false, false, false, false, false, true, true],
    [true, true, false, false, false, false, false, false, false, false, false, false, true, true],
    [true, true, false, false, false, false, false, false, false, false, false, false, true, true],
    [true, true, false, false, false, false, false, false, false, false, false, false, true, true],
    [true, true, false, false, false, false, false, false, false, false, false, false, true, true],
    [true, true, true, false, false, false, false, false, false, false, false, true, true, true],
    [true, true, true, true, false, false, false, false, false, false, true, true, true, true],
    [false, true, true, true, true, true, true, true, true, true, true, true, true, false],
    [false, false, true, true, true, true, true, true, true, true, true, true, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false],
  ],

  // Level 15
  [
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [false, false, false, false, 2, true, false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false],
  ],

  // Level 16: Double Diamond
  [
    [false, false, false, true, true, true, false, false, true, true, true, false, false, false],
    [false, false, true, true, true, true, true, false, true, true, true, true, false, false],
    [false, true, true, true, true, true, true, true, true, true, true, true, true, false],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, 2, 2, 2, 2, true, true, true, true, true],
    [true, true, true, true, 2, 2, 2, 2, 2, 2, true, true, true, true],
    [false, true, true, 2, 2, 2, 2, 2, 2, 2, 2, true, true, false],
    [false, false, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, false, false],
    [false, false, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, false, false],
    [false, true, true, 2, 2, 2, 2, 2, 2, 2, 2, true, true, false],
    [true, true, true, true, 2, 2, 2, 2, 2, 2, true, true, true, true],
    [true, true, true, true, true, 2, 2, 2, 2, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [false, true, true, true, true, true, true, true, true, true, true, true, true, false],
    [false, false, true, true, true, true, true, true, true, true, true, true, false, false],
    [false, false, false, true, true, true, false, false, true, true, true, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false],
  ],

  // Level 17: Tunnel
  [
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [2, 2, true, true, true, true, true, true, true, true, true, true, 2, 2],
    [2, 2, true, true, true, true, true, true, true, true, true, true, 2, 2],
    [2, 2, true, true, false, false, false, false, false, false, true, true, 2, 2],
    [2, 2, true, true, false, false, false, false, false, false, true, true, 2, 2],
    [2, 2, true, true, false, false, false, false, false, false, true, true, 2, 2],
    [2, 2, true, true, false, false, false, false, false, false, true, true, 2, 2],
    [2, 2, true, true, false, false, false, false, false, false, true, true, 2, 2],
    [2, 2, true, true, false, false, false, false, false, false, true, true, 2, 2],
    [2, 2, true, true, false, false, false, false, false, false, true, true, 2, 2],
    [2, 2, true, true, false, false, false, false, false, false, true, true, 2, 2],
    [2, 2, true, true, true, true, true, true, true, true, true, true, 2, 2],
    [2, 2, true, true, true, true, true, true, true, true, true, true, 2, 2],
    [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
    [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false],
  ],

  // Level 18: Plus Sign
  [
    [false, false, false, false, true, true, true, true, true, true, false, false, false, false],
    [false, false, false, false, true, true, true, true, true, true, false, false, false, false],
    [false, false, false, false, true, true, true, true, true, true, false, false, false, false],
    [false, false, false, false, true, true, true, true, true, true, false, false, false, false],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, 2, 2, true, true, true, true, true, true],
    [true, true, true, true, true, true, 2, 2, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [false, false, false, false, true, true, true, true, true, true, false, false, false, false],
    [false, false, false, false, true, true, true, true, true, true, false, false, false, false],
    [false, false, false, false, true, true, true, true, true, true, false, false, false, false],
    [false, false, false, false, true, true, true, true, true, true, false, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false],
  ],

  // Level 19: Waves
  [
    [true, true, false, false, false, false, true, true, false, false, false, false, true, true],
    [true, true, true, false, false, true, true, true, true, false, false, true, true, true],
    [false, true, true, true, true, true, true, false, true, true, true, true, true, false],
    [false, false, true, true, true, true, false, false, false, true, true, true, true, false],
    [true, true, false, false, false, false, true, true, false, false, false, false, true, true],
    [true, true, true, false, false, true, true, true, true, false, false, true, true, true],
    [false, true, true, true, true, true, true, false, true, true, true, true, true, false],
    [false, false, true, true, true, true, false, false, false, true, true, true, true, false],
    [true, true, false, false, false, false, true, true, false, false, false, false, true, true],
    [true, true, true, false, false, true, true, true, true, false, false, true, true, true],
    [false, true, true, true, true, true, true, false, true, true, true, true, true, false],
    [false, false, true, true, true, true, false, false, false, true, true, true, true, false],
    [true, true, false, false, false, false, true, true, false, false, false, false, true, true],
    [true, true, true, false, false, true, true, true, true, false, false, true, true, true],
    [false, true, true, true, true, true, true, false, true, true, true, true, true, false],
    [false, false, true, true, true, true, false, false, false, true, true, true, true, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false],
  ],

  // Level 20: Fort
  [
    [2, 2, true, true, true, 2, 2, 2, 2, true, true, true, 2, 2],
    [2, 2, true, true, true, 2, 2, 2, 2, true, true, true, 2, 2],
    [2, 2, true, true, true, 2, 2, 2, 2, true, true, true, 2, 2],
    [2, 2, 2, 2, true, true, 2, 2, 2, 2, 2, 2, 2, 2],
    [2, true, true, true, true, true, true, true, true, true, true, true, true, 2],
    [2, true, true, true, true, true, true, true, true, true, true, true, true, 2],
    [2, true, true, 2, 2, 2, 2, 2, 2, 2, 2, true, true, 2],
    [2, true, true, 2, true, true, true, true, true, true, 2, true, true, 2],
    [2, true, true, 2, true, true, true, true, true, true, 2, true, true, 2],
    [2, true, true, 2, true, true, true, true, true, true, 2, true, true, 2],
    [2, true, true, 2, true, true, true, true, true, true, 2, true, true, 2],
    [2, true, true, 2, 2, 2, 2, 2, 2, 2, 2, true, true, 2],
    [2, true, true, true, true, true, true, true, true, true, true, true, true, 2],
    [2, true, true, true, true, true, true, true, true, true, true, true, true, 2],
    [2, 2, 2, 2, 2, 2, true, true, true, true, true, 2, 2, 2],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false],
  ],

  // Level 21: Spiral
  [
    [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, 2],
    [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, true, 2],
    [2, true, true, true, true, true, true, true, true, true, true, 2, true, 2],
    [2, true, 2, 2, 2, 2, 2, 2, 2, 2, true, 2, true, 2],
    [2, true, 2, true, true, true, true, true, true, 2, true, 2, true, 2],
    [2, true, 2, true, 2, 2, 2, 2, true, 2, true, 2, true, 2],
    [2, true, 2, true, 2, true, true, 2, true, 2, true, 2, true, 2],
    [2, true, 2, true, 2, 2, true, 2, true, 2, true, 2, true, 2],
    [2, true, 2, true, true, true, true, 2, true, 2, true, 2, true, 2],
    [2, true, 2, 2, 2, 2, 2, 2, true, 2, true, 2, true, 2],
    [2, true, true, true, true, true, true, true, true, 2, true, 2, true, 2],
    [2, true, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, true, 2],
    [2, true, true, true, true, true, true, true, true, true, true, true, true, 2],
    [2, 2, 2, 2, 2, 2, true, 2, 2, 2, 2, 2, 2, 2],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false],
  ],

  // Level 22: Hourglass
  [
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [false, true, true, true, true, true, true, true, true, true, true, true, true, false],
    [false, false, true, true, true, true, true, true, true, true, true, true, false, false],
    [false, false, false, true, true, true, true, true, true, true, true, false, false, false],
    [false, false, false, false, true, true, true, true, true, true, false, false, false, false],
    [false, false, false, false, false, true, true, true, true, false, false, false, false, false],
    [false, false, false, false, false, false, true, true, false, false, false, false, false, false],
    [false, false, false, false, false, false, 2, 2, false, false, false, false, false, false],
    [false, false, false, false, false, false, true, true, false, false, false, false, false, false],
    [false, false, false, false, false, true, true, true, true, false, false, false, false, false],
    [false, false, false, false, true, true, true, true, true, true, false, false, false, false],
    [false, false, false, true, true, true, true, true, true, true, true, false, false, false],
    [false, false, true, true, true, true, true, true, true, true, true, true, false, false],
    [false, true, true, true, true, true, true, true, true, true, true, true, true, false],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false],
  ],

  // Level 23: Grid with Holes
  [
    [true, true, true, false, true, true, true, true, true, true, false, true, true, true],
    [true, true, true, false, true, true, true, true, true, true, false, true, true, true],
    [true, true, true, false, true, true, true, true, true, true, false, true, true, true],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [true, true, true, false, true, true, true, true, true, true, false, true, true, true],
    [true, true, true, false, true, true, 2, 2, true, true, false, true, true, true],
    [true, true, true, false, true, true, 2, 2, true, true, false, true, true, true],
    [true, true, true, false, true, true, true, true, true, true, false, true, true, true],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [true, true, true, false, true, true, true, true, true, true, false, true, true, true],
    [true, true, true, false, true, true, true, true, true, true, false, true, true, true],
    [true, true, true, false, true, true, true, true, true, true, false, true, true, true],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [true, true, true, false, true, true, true, true, true, true, false, true, true, true],
    [true, true, true, false, true, true, true, true, true, true, false, true, true, true],
    [true, true, true, false, true, true, true, true, true, true, false, true, true, true],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false],
  ],

  // Level 24: Butterfly
  [
    [false, false, true, true, true, false, false, false, false, true, true, true, false, false],
    [false, true, true, true, true, true, false, false, true, true, true, true, true, false],
    [true, true, true, false, true, true, true, true, true, true, false, true, true, true],
    [true, true, false, false, false, true, true, true, true, false, false, false, true, true],
    [true, true, false, false, false, false, true, true, false, false, false, false, true, true],
    [true, true, false, false, false, 2, 2, 2, 2, false, false, false, true, true],
    [false, true, true, false, 2, 2, 2, 2, 2, 2, false, true, true, false],
    [false, false, true, true, 2, 2, 2, 2, 2, 2, true, true, false, false],
    [false, false, true, true, 2, 2, 2, 2, 2, 2, true, true, false, false],
    [false, true, true, false, 2, 2, 2, 2, 2, 2, false, true, true, false],
    [true, true, false, false, false, 2, 2, 2, 2, false, false, false, true, true],
    [true, true, false, false, false, false, true, true, false, false, false, false, true, true],
    [true, true, false, false, false, true, true, true, true, false, false, false, true, true],
    [true, true, true, false, true, true, true, true, true, true, false, true, true, true],
    [false, true, true, true, true, true, false, false, true, true, true, true, true, false],
    [false, false, true, true, true, false, false, false, false, true, true, true, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false],
  ],

  // Level 25: Shield
  [
    [false, false, false, false, false, true, true, true, true, false, false, false, false, false],
    [false, false, false, false, true, true, true, true, true, true, false, false, false, false],
    [false, false, false, true, true, true, 2, 2, true, true, true, false, false, false],
    [false, false, true, true, true, 2, 2, 2, 2, true, true, true, false, false],
    [false, true, true, true, 2, 2, 2, 2, 2, 2, true, true, true, false],
    [true, true, true, true, 2, 2, 2, 2, 2, 2, true, true, true, true],
    [true, true, true, true, true, 2, 2, 2, 2, true, true, true, true, true],
    [true, true, true, true, true, true, 2, 2, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [false, true, true, true, true, true, true, true, true, true, true, true, true, false],
    [false, false, true, true, true, true, true, true, true, true, true, true, false, false],
    [false, false, false, true, true, true, true, true, true, true, true, false, false, false],
    [false, false, false, false, true, true, true, true, true, true, false, false, false, false],
    [false, false, false, false, false, true, true, true, true, false, false, false, false, false],
    [false, false, false, false, false, false, true, true, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false],
  ],

  // Level 26: Target
  [
    [false, false, false, true, true, true, true, true, true, true, true, false, false, false],
    [false, false, true, true, true, true, true, true, true, true, true, true, false, false],
    [false, true, true, true, 2, 2, 2, 2, 2, 2, true, true, true, false],
    [true, true, true, 2, 2, 2, 2, 2, 2, 2, 2, true, true, true],
    [true, true, 2, 2, 2, 2, true, true, 2, 2, 2, 2, true, true],
    [true, true, 2, 2, 2, true, true, true, true, 2, 2, 2, true, true],
    [true, true, 2, 2, true, true, true, true, true, true, 2, 2, true, true],
    [true, true, 2, 2, true, true, true, true, true, true, 2, 2, true, true],
    [true, true, 2, 2, true, true, true, true, true, true, 2, 2, true, true],
    [true, true, 2, 2, true, true, true, true, true, true, 2, 2, true, true],
    [true, true, 2, 2, 2, true, true, true, true, 2, 2, 2, true, true],
    [true, true, 2, 2, 2, 2, true, true, 2, 2, 2, 2, true, true],
    [true, true, true, 2, 2, 2, false, false, 2, 2, 2, true, true, true],
    [false, true, true, true, 2, false, false, 2, 2, 2, true, true, true, false],
    [false, false, true, true, true, true, true, true, true, true, true, true, false, false],
    [false, false, false, true, true, true, true, true, true, true, true, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false],
  ],

  // Level 27: Ladder
  [
    [true, true, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, true, true],
    [true, true, 2, false, false, false, false, false, false, false, false, 2, true, true],
    [true, true, 2, false, false, false, false, false, false, false, false, 2, true, true],
    [true, true, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, true, true],
    [true, true, 2, false, false, false, false, false, false, false, false, 2, true, true],
    [true, true, 2, false, false, false, false, false, false, false, false, 2, true, true],
    [true, true, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, true, true],
    [true, true, 2, false, false, false, false, false, false, false, false, 2, true, true],
    [true, true, 2, false, false, false, false, false, false, false, false, 2, true, true],
    [true, true, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, true, true],
    [true, true, 2, false, false, false, false, false, false, false, false, 2, true, true],
    [true, true, 2, false, false, false, false, false, false, false, false, 2, true, true],
    [true, true, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, true, true],
    [true, true, 2, false, false, false, false, false, false, false, false, 2, true, true],
    [true, true, 2, false, false, false, false, false, false, false, false, 2, true, true],
    [true, true, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, true, true],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false],
  ],

  // Level 28: Hexagon
  [
    [false, false, false, false, true, true, true, true, true, true, false, false, false, false],
    [false, false, false, true, true, true, true, true, true, true, true, false, false, false],
    [false, false, true, true, true, true, true, true, true, true, true, true, false, false],
    [false, true, true, true, true, 2, 2, 2, 2, true, true, true, true, false],
    [true, true, true, true, 2, 2, 2, 2, 2, 2, true, true, true, true],
    [true, true, true, true, 2, 2, 2, 2, 2, 2, true, true, true, true],
    [true, true, true, true, 2, 2, 2, 2, 2, 2, true, true, true, true],
    [true, true, true, true, 2, 2, 2, 2, 2, 2, true, true, true, true],
    [true, true, true, true, 2, 2, 2, 2, 2, 2, true, true, true, true],
    [true, true, true, true, 2, 2, 2, 2, 2, 2, true, true, true, true],
    [true, true, true, true, 2, 2, 2, 2, 2, 2, true, true, true, true],
    [true, true, true, true, 2, 2, 2, 2, 2, 2, true, true, true, true],
    [false, true, true, true, true, 2, 2, 2, 2, true, true, true, true, false],
    [false, false, true, true, true, true, true, true, true, true, true, true, false, false],
    [false, false, false, true, true, true, true, true, true, true, true, false, false, false],
    [false, false, false, false, true, true, true, true, true, true, false, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false],
  ],

  // Level 29: Lightning
  [
    [false, false, false, false, true, true, true, true, true, false, false, false, false, false],
    [false, false, false, true, true, true, true, true, true, false, false, false, false, false],
    [false, false, true, true, true, true, true, true, true, false, false, false, false, false],
    [false, true, true, true, true, true, true, true, false, false, false, false, false, false],
    [true, true, true, true, true, true, true, false, false, false, false, false, false, false],
    [true, true, true, true, true, true, true, true, true, true, true, true, false, false],
    [false, false, false, true, true, true, true, true, true, true, true, false, false, false],
    [false, false, false, false, true, true, true, true, true, true, false, false, false, false],
    [false, false, false, false, false, true, true, true, true, true, false, false, false, false],
    [false, false, false, false, false, false, true, true, true, true, true, false, false, false],
    [false, false, false, false, false, false, false, true, true, true, true, true, false, false],
    [false, false, false, false, false, false, false, false, true, true, true, true, true, false],
    [false, false, false, false, false, false, false, false, false, true, true, true, true, true],
    [false, false, false, false, false, false, false, false, false, false, true, true, true, true],
    [false, false, false, false, false, false, false, false, false, false, false, true, true, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false],
  ],

  // Level 30: Castle
  [
    [2, false, 2, false, 2, 2, 2, 2, 2, 2, 2, false, 2, false],
    [2, false, 2, false, 2, 2, 2, 2, 2, 2, 2, false, 2, false],
    [2, 2, 2, 2, 2, true, true, true, true, true, true, 2, 2, 2],
    [2, true, true, true, true, true, true, true, true, true, true, true, true, 2],
    [2, true, true, true, true, true, true, true, true, true, true, true, true, 2],
    [2, true, true, 2, 2, 2, 2, 2, 2, 2, 2, true, true, 2],
    [2, true, true, true, true, true, true, true, true, true, 2, true, true, 2],
    [2, true, true, true, true, true, true, true, true, true, 2, true, true, 2],
    [2, true, true, true, true, true, true, true, true, true, 2, true, true, 2],
    [2, true, true, true, true, true, 2, 2, true, true, 2, true, true, 2],
    [2, true, true, 2, true, true, 2, 2, true, true, 2, true, true, 2],
    [2, true, true, 2, true, true, true, true, true, true, 2, true, true, 2],
    [2, true, true, 2, true, true, true, true, true, true, 2, true, true, 2],
    [2, true, true, 2, 2, 2, 2, 2, 2, 2, 2, true, true, 2],
    [2, true, true, true, true, true, true, true, true, true, true, true, true, 2],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false],
  ],

  // Level 31: Dense Challenge
  [
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
  ],

  // Level 32: Cross in Square
  [
    [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
    [2, true, true, true, true, true, true, true, true, true, true, true, true, 2],
    [2, true, true, true, true, true, true, true, true, true, true, true, true, 2],
    [2, true, true, true, true, true, 2, 2, true, true, true, true, true, 2],
    [2, true, true, true, true, true, 2, 2, true, true, true, true, true, 2],
    [2, true, true, true, true, true, 2, 2, true, true, true, true, true, 2],
    [2, true, true, 2, 2, 2, 2, 2, 2, 2, 2, true, true, 2],
    [2, true, true, 2, 2, 2, 2, 2, 2, 2, 2, true, true, 2],
    [2, true, true, true, true, true, 2, 2, true, true, true, true, true, 2],
    [2, true, true, true, true, true, 2, 2, true, true, true, true, true, 2],
    [2, true, true, true, true, true, 2, 2, true, true, true, true, true, 2],
    [2, true, true, true, true, true, true, true, true, true, true, true, true, 2],
    [2, true, true, true, true, true, true, true, true, true, true, true, true, 2],
    [2, 2, true, true, 2, 2, 2, 2, 2, 2, true, true, 2, 2],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false],
  ],

  // Level 33: Multiple Targets
  [
    [true, true, 2, 2, true, true, false, false, true, true, 2, 2, true, true],
    [true, 2, 2, 2, 2, true, false, false, true, 2, 2, 2, 2, true],
    [2, 2, 2, 2, 2, 2, false, false, 2, 2, 2, 2, 2, 2],
    [2, 2, 2, 2, 2, 2, false, false, 2, 2, 2, 2, 2, 2],
    [true, 2, 2, 2, 2, true, false, false, true, 2, 2, 2, 2, true],
    [true, true, 2, 2, true, true, false, false, true, true, 2, 2, true, true],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [true, true, 2, 2, true, true, false, false, true, true, 2, 2, true, true],
    [true, 2, 2, 2, 2, true, false, false, true, 2, 2, 2, 2, true],
    [2, 2, 2, 2, 2, 2, false, false, 2, 2, 2, 2, 2, 2],
    [2, 2, 2, 2, 2, 2, false, false, 2, 2, 2, 2, 2, 2],
    [true, 2, 2, 2, 2, true, false, false, true, 2, 2, 2, 2, true],
    [true, true, 2, 2, true, true, false, false, true, true, 2, 2, true, true],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false],
  ],

  // Level 34: Corners
  [
    [true, true, true, true, false, false, false, false, false, false, true, true, true, true],
    [true, true, true, true, false, false, false, false, false, false, true, true, true, true],
    [true, true, true, true, false, false, false, false, false, false, true, true, true, true],
    [true, true, true, true, false, false, false, false, false, false, true, true, true, true],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, 2, 2, false, false, false, false, false, false],
    [false, false, false, false, false, false, 2, 2, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [true, true, true, true, false, false, false, false, false, false, true, true, true, true],
    [true, true, true, true, false, false, false, false, false, false, true, true, true, true],
    [true, true, true, true, false, false, false, false, false, false, true, true, true, true],
    [true, true, true, true, false, false, false, false, false, false, true, true, true, true],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false],
  ],

  // Level 35: Diagonal Waves
  [
    [true, false, false, false, false, false, false, false, false, false, false, false, false, true],
    [true, true, false, false, false, false, false, false, false, false, false, false, true, true],
    [false, true, true, false, false, false, false, false, false, false, false, true, true, false],
    [false, false, true, true, false, false, false, false, false, false, true, true, false, false],
    [false, false, false, true, true, false, false, false, false, true, true, false, false, false],
    [false, false, false, false, true, true, false, false, true, true, false, false, false, false],
    [false, false, false, false, false, true, true, true, true, false, false, false, false, false],
    [false, false, false, false, false, false, true, true, false, false, false, false, false, false],
    [false, false, false, false, false, false, true, true, false, false, false, false, false, false],
    [false, false, false, false, false, true, true, true, true, false, false, false, false, false],
    [false, false, false, false, true, true, false, false, true, true, false, false, false, false],
    [false, false, false, true, true, false, false, false, false, true, true, false, false, false],
    [false, false, true, true, false, false, false, false, false, false, true, true, false, false],
    [false, true, true, false, false, false, false, false, false, false, false, true, true, false],
    [true, true, false, false, false, false, false, false, false, false, false, false, true, true],
    [true, false, false, false, false, false, false, false, false, false, false, false, false, true],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false],
  ],

  // Level 36: Fortress
  [
    [2, false, 2, false, 2, false, 2, 2, false, 2, false, 2, false, 2],
    [2, false, 2, false, 2, false, 2, 2, false, 2, false, 2, false, 2],
    [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
    [2, true, true, true, true, true, true, true, true, true, true, true, true, 2],
    [2, true, true, true, true, true, true, true, true, true, true, true, true, 2],
    [2, true, true, 2, 2, 2, 2, 2, 2, 2, 2, true, true, 2],
    [2, true, true, 2, true, true, true, true, true, true, 2, true, true, 2],
    [2, true, true, 2, true, true, true, true, true, true, 2, true, true, 2],
    [2, true, true, 2, true, true, 2, 2, true, true, 2, true, true, 2],
    [2, true, true, 2, true, true, 2, 2, true, true, 2, true, true, 2],
    [2, true, true, 2, true, true, 2, 2, true, true, 2, true, true, 2],
    [2, true, true, 2, true, true, 2, 2, true, true, 2, true, true, 2],
    [2, true, true, 2, true, true, true, true, true, true, 2, true, true, 2],
    [2, true, true, 2, true, true, true, true, true, true, 2, true, true, 2],
    [2, true, true, 2, 2, 2, 2, 2, 2, 2, 2, true, true, 2],
    [2, true, true, true, true, true, true, true, true, true, true, true, true, 2],
    [2, true, true, true, true, true, true, true, true, true, true, true, true, 2],
    [2, 2, 2, false, false, 2, 2, 2, 2, 2, 2, 2, 2, 2],
  ],

  // Level 37: Dense Grid
  [
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
  ],

  // Level 38: Double Frame
  [
    [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
    [2, true, true, true, true, true, true, true, true, true, true, true, true, 2],
    [2, true, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, true, 2],
    [2, true, 2, true, true, true, true, true, true, true, true, 2, true, 2],
    [2, true, 2, true, 2, 2, 2, 2, 2, 2, true, 2, true, 2],
    [2, true, 2, true, 2, true, true, true, true, 2, true, 2, true, 2],
    [2, true, 2, true, 2, true, true, true, true, 2, true, 2, true, 2],
    [2, true, 2, true, 2, true, true, true, true, 2, true, 2, true, 2],
    [2, true, 2, true, 2, true, true, true, true, 2, true, 2, true, 2],
    [2, true, 2, true, 2, true, true, true, true, 2, true, 2, true, 2],
    [2, true, 2, true, 2, true, true, true, true, 2, true, 2, true, 2],
    [2, true, 2, true, 2, 2, 2, 2, 2, 2, true, 2, true, 2],
    [2, true, 2, true, true, true, true, true, true, true, true, 2, true, 2],
    [2, true, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, true, 2],
    [2, true, true, true, true, true, true, true, true, true, true, true, true, 2],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false],
  ],

  // Level 39: Teeth
  [
    [true, false, true, false, true, false, true, false, true, false, true, false, true, false],
    [true, false, true, false, true, false, true, false, true, false, true, false, true, false],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [false, true, false, true, false, true, false, true, false, true, false, true, false, true],
    [false, true, false, true, false, true, false, true, false, true, false, true, false, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, false, true, false, true, false, true, false, true, false, true, false, true, false],
    [true, false, true, false, true, false, true, false, true, false, true, false, true, false],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
  ],

  // Level 40: Ultimate Challenge
  [
    [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
    [2, true, true, true, true, true, true, true, true, true, true, true, true, 2],
    [2, true, 2, 2, 2, 2, 2, true, true, 2, 2, 2, true, 2],
    [2, true, 2, true, true, true, true, true, true, true, true, 2, true, 2],
    [2, true, 2, true, 2, 2, 2, 2, 2, 2, true, 2, true, 2],
    [2, true, 2, true, 2, true, true, true, true, 2, true, 2, true, 2],
    [2, true, 2, true, 2, true, 2, 2, true, 2, true, 2, true, 2],
    [2, true, 2, true, 2, true, 2, 2, true, 2, true, 2, true, 2],
    [2, true, 2, true, 2, true, 2, 2, true, 2, true, 2, true, 2],
    [2, true, 2, true, 2, true, 2, 2, true, 2, true, 2, true, 2],
    [2, true, 2, true, 2, true, true, true, true, 2, true, 2, true, 2],
    [2, true, 2, true, 2, 2, 2, 2, 2, 2, true, 2, true, 2],
    [2, true, 2, true, true, true, true, true, true, true, true, 2, true, 2],
    [2, true, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, true, 2],
    [2, true, true, true, true, true, true, true, true, true, true, true, true, 2],
    [2, 2, 2, false, false, false, false, 2, 2, 2, 2, 2, 2, 2],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false],
  ],

  // Levels 41-50: Repeat patterns with maximum difficulty
  // Level 41
  [
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
  ],

  // Level 42
  [
    [2, 2, 2, 2, true, true, true, 2, 2, 2, 2, 2, 2, 2],
    [2, true, true, true, true, true, true, true, true, true, true, true, true, 2],
    [2, true, true, true, true, true, true, true, true, true, true, true, true, 2],
    [2, true, true, true, true, true, true, true, true, true, true, true, true, 2],
    [false, true, true, true, true, true, true, true, true, true, true, true, true, false],
    [false, true, true, true, true, true, true, true, true, true, true, true, true, false],
    [false, true, true, true, true, true, true, true, true, true, true, true, true, false],
    [false, true, true, true, true, true, true, true, true, true, true, true, true, false],
    [false, true, true, true, true, true, true, true, true, true, true, true, true, false],
    [2, true, true, true, true, true, true, true, true, true, true, true, true, 2],
    [2, true, true, true, true, true, true, true, true, true, true, true, true, 2],
    [2, true, true, true, true, true, true, true, true, true, true, true, true, 2],
    [2, true, true, true, true, true, true, true, true, true, true, true, true, 2],
    [2, true, true, true, true, true, true, true, true, true, true, true, true, 2],
    [2, true, true, true, true, true, true, true, true, true, true, true, true, 2],
    [2, true, true, true, true, true, true, true, true, true, true, true, true, 2],
    [2, true, true, true, true, true, true, true, true, true, true, true, true, 2],
    [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
  ],

  // Level 43-50: Continue with variations
  [
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
  ],

  [
    [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
    [2, true, true, true, true, true, true, true, true, true, true, true, true, 2],
    [2, true, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, true, 2],
    [2, true, 2, true, true, true, true, true, true, true, true, 2, true, 2],
    [2, true, true, true, true, true, true, true, true, true, true, 2, true, 2],
    [2, true, true, true, true, true, true, true, true, true, true, 2, true, 2],
    [2, true, true, true, true, true, true, true, true, true, true, 2, true, 2],
    [2, true, 2, true, true, true, true, true, true, true, true, true, true, 2],
    [2, true, 2, true, true, true, true, true, true, true, true, 2, true, 2],
    [2, true, 2, true, true, true, true, true, true, true, true, 2, true, 2],
    [2, true, 2, true, true, true, true, true, true, true, true, 2, true, 2],
    [2, true, 2, true, true, true, true, true, true, true, true, 2, true, 2],
    [2, true, 2, true, true, true, true, true, true, true, true, 2, true, 2],
    [2, true, 2, true, true, true, true, true, true, true, true, 2, true, 2],
    [2, true, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, true, 2],
    [2, true, true, true, true, true, true, true, true, true, true, true, true, 2],
    [2, 2, 2, 2, 2, false, false, false, false, 2, 2, 2, 2, 2],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false],
  ],

  [
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
  ],

  [
    [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [2, true, true, true, true, true, true, true, true, true, true, true, true, 2],
    [2, true, true, true, true, true, true, true, true, true, true, true, true, 2],
    [2, true, true, true, true, true, true, true, true, true, true, true, true, 2],
    [2, true, true, true, true, true, true, true, true, true, true, true, true, 2],
    [2, true, true, true, true, true, true, true, true, true, true, true, true, 2],
    [2, true, true, true, true, true, true, true, true, true, true, true, true, 2],
    [2, true, true, true, true, true, true, true, true, true, true, true, true, 2],
    [2, true, true, true, true, true, true, true, true, true, true, true, true, 2],
    [2, true, true, true, true, true, true, true, true, true, true, true, true, 2],
    [2, true, true, true, true, true, true, true, true, true, true, true, true, 2],
    [2, true, true, true, true, true, true, true, true, true, true, true, true, 2],
    [2, true, true, true, true, true, true, true, true, true, true, true, true, 2],
    [2, true, true, true, true, true, true, true, true, true, true, true, true, 2],
    [2, 2, 2, 2, 2, 2, false, false, false, false, 2, 2, 2, 2],
  ],

  [
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
  ],

  [
    [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
    [2, true, true, true, true, true, true, true, true, true, true, true, true, 2],
    [2, true, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, true, 2],
    [2, true, 2, true, true, true, true, true, true, true, true, 2, true, 2],
    [true, true, 2, true, 2, 2, 2, 2, 2, 2, true, 2, true, 2],
    [true, true, 2, true, 2, true, true, true, true, 2, true, 2, true, 2],
    [true, true, 2, true, 2, true, true, true, true, 2, true, 2, true, 2],
    [true, true, 2, true, true, true, true, true, true, 2, true, 2, true, 2],
    [2, true, 2, true, 2, true, true, true, true, 2, true, 2, true, 2],
    [2, true, 2, true, 2, true, true, true, true, 2, true, 2, true, 2],
    [2, true, 2, true, 2, true, true, true, true, 2, true, 2, true, 2],
    [2, true, 2, true, 2, 2, 2, 2, 2, 2, true, 2, true, 2],
    [2, true, 2, true, true, true, true, true, true, true, true, 2, true, 2],
    [2, true, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, true, 2],
    [2, true, true, true, true, true, true, true, true, true, true, true, true, 2],
    [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false],
  ],

  [
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
  ],

  [
    [2, false, false, false, false, false, 2, 2, 2, 2, 2, 2, 2, 2],
    [2, true, true, true, true, true, true, true, true, true, true, true, true, 2],
    [2, true, true, true, true, true, true, true, true, true, true, true, true, 2],
    [2, true, true, true, true, true, true, true, true, true, true, true, true, 2],
    [2, true, true, false, false, true, true, true, true, false, false, true, true, 2],
    [2, true, true, false, false, true, true, true, true, false, false, true, true, 2],
    [2, true, true, true, true, true, true, true, true, true, true, true, true, 2],
    [2, true, true, true, true, false, false, false, true, true, true, true, true, 2],
    [2, true, true, true, true, false, false, false, true, true, true, true, true, 2],
    [2, true, true, true, true, true, true, true, true, true, true, true, true, 2],
    [2, true, true, true, true, true, true, true, true, true, true, true, true, 2],
    [2, true, true, true, true, true, true, true, true, true, true, true, true, 2],
    [2, true, true, true, true, true, true, true, true, true, true, true, true, 2],
    [2, true, true, true, true, true, true, true, true, true, true, true, true, 2],
    [2, true, true, true, true, true, true, true, true, true, true, true, true, 2],
    [2, true, true, true, true, true, true, true, true, true, true, true, true, 2],
    [2, true, true, true, true, true, true, true, true, true, true, true, true, 2],
    [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
  ],
];
