// Level layouts - each layout is a 2D array where:
// false = no brick, true = normal brick, 2 = indestructible brick (from level 10+)
// Returns the number of hits required for a brick at this position and level
export const getBrickHits = (level: number, row: number): number => {
  if (level < 3) return 1;
  if (level < 5) return row < 2 ? 2 : 1;
  if (level < 7) return row < 3 ? 2 : 1;
  if (level < 9) return row < 2 ? 3 : row < 4 ? 2 : 1;
  return row < 3 ? 3 : row < 5 ? 2 : 1;
};

export const levelLayouts: (boolean | number)[][][] = [
  // Level 1: Classic Rows
  [
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false],
  ],

  // Level 2: Diamond
  [
    [false, false, false, false, false, false, true, true, false, false, false, false, false, false],
    [false, false, false, false, false, true, true, true, true, false, false, false, false, false],
    [false, false, false, false, true, true, true, true, true, true, false, false, false, false],
    [false, false, false, true, true, true, true, true, true, true, true, false, false, false],
    [false, false, true, true, true, true, true, true, true, true, true, true, false, false],
    [false, true, true, true, true, true, true, true, true, true, true, true, true, false],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [false, true, true, true, true, true, true, true, true, true, true, true, true, false],
    [false, false, true, true, true, true, true, true, true, true, true, true, false, false],
    [false, false, false, true, true, true, true, true, true, true, true, false, false, false],
    [false, false, false, false, true, true, true, true, true, true, false, false, false, false],
    [false, false, false, false, false, true, true, true, true, false, false, false, false, false],
    [false, false, false, false, false, false, true, true, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false],
  ],

  // Level 3: Heart Pattern
  [
    [false, false, false, true, true, true, false, false, true, true, true, false, false, false],
    [false, false, true, true, true, true, true, true, true, true, true, true, false, false],
    [false, true, true, true, true, true, true, true, true, true, true, true, true, false],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [false, true, true, true, true, true, true, true, true, true, true, true, true, false],
    [false, false, true, true, true, true, true, true, true, true, true, true, false, false],
    [false, false, false, true, true, true, true, true, true, true, true, false, false, false],
    [false, false, false, false, true, true, true, true, true, true, false, false, false, false],
    [false, false, false, false, false, true, true, true, true, false, false, false, false, false],
    [false, false, false, false, false, false, true, true, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false],
  ],

  // Level 4: Full Dense Grid
  [
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false],
  ],

  // Level 5: Pyramid
  [
    [false, false, false, false, false, false, true, true, false, false, false, false, false, false],
    [false, false, false, false, false, true, true, true, true, false, false, false, false, false],
    [false, false, false, false, true, true, true, true, true, true, false, false, false, false],
    [false, false, false, true, true, true, true, true, true, true, true, false, false, false],
    [false, false, true, true, true, true, true, true, true, true, true, true, false, false],
    [false, true, true, true, true, true, true, true, true, true, true, true, true, false],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false],
  ],

  // Level 6: Checkerboard
  [
    [true, false, true, false, true, false, true, false, true, false, true, false, true, false],
    [false, true, false, true, false, true, false, true, false, true, false, true, false, true],
    [true, false, true, false, true, false, true, false, true, false, true, false, true, false],
    [false, true, false, true, false, true, false, true, false, true, false, true, false, true],
    [true, false, true, false, true, false, true, false, true, false, true, false, true, false],
    [false, true, false, true, false, true, false, true, false, true, false, true, false, true],
    [true, false, true, false, true, false, true, false, true, false, true, false, true, false],
    [false, true, false, true, false, true, false, true, false, true, false, true, false, true],
    [true, false, true, false, true, false, true, false, true, false, true, false, true, false],
    [false, true, false, true, false, true, false, true, false, true, false, true, false, true],
    [true, false, true, false, true, false, true, false, true, false, true, false, true, false],
    [false, true, false, true, false, true, false, true, false, true, false, true, false, true],
    [true, false, true, false, true, false, true, false, true, false, true, false, true, false],
    [false, true, false, true, false, true, false, true, false, true, false, true, false, true],
    [true, false, true, false, true, false, true, false, true, false, true, false, true, false],
    [false, true, false, true, false, true, false, true, false, true, false, true, false, true],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false],
  ],

  // Level 7: X Pattern
  [
    [true, true, false, false, false, false, false, false, false, false, false, false, true, true],
    [true, true, true, false, false, false, false, false, false, false, false, true, true, true],
    [false, true, true, true, false, false, false, false, false, false, true, true, true, false],
    [false, false, true, true, true, false, false, false, false, true, true, true, false, false],
    [false, false, false, true, true, true, false, false, true, true, true, false, false, false],
    [false, false, false, false, true, true, true, true, true, true, false, false, false, false],
    [false, false, false, false, false, true, true, true, true, false, false, false, false, false],
    [false, false, false, false, false, false, true, true, false, false, false, false, false, false],
    [false, false, false, false, false, false, true, true, false, false, false, false, false, false],
    [false, false, false, false, false, true, true, true, true, false, false, false, false, false],
    [false, false, false, false, true, true, true, true, true, true, false, false, false, false],
    [false, false, false, true, true, true, false, false, true, true, true, false, false, false],
    [false, false, true, true, true, false, false, false, false, true, true, true, false, false],
    [false, true, true, true, false, false, false, false, false, false, true, true, true, false],
    [true, true, true, false, false, false, false, false, false, false, false, true, true, true],
    [true, true, false, false, false, false, false, false, false, false, false, false, true, true],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false],
  ],

  // Level 8: Dense Grid
  [
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false, false, false, false, false, false, false],
  ],

  // Level 9: Full Grid
  [
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true, true, true, true, true, true, true],
  ],

  // Level 10: With Indestructible Frame (2 = indestructible)
  [
    [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
    [2, true, true, true, true, true, true, true, true, true, true, true, true, 2],
    [2, true, true, true, true, true, true, true, true, true, true, true, true, 2],
    [2, true, true, true, true, true, true, true, true, true, true, true, true, 2],
    [2, true, true, true, true, true, true, true, true, true, true, true, true, 2],
    [2, 2, 2, true, true, true, true, true, true, true, true, 2, 2, 2],
    [false, false, 2, true, true, true, true, true, true, true, true, 2, false, false],
    [false, false, 2, true, true, true, true, true, true, true, true, 2, false, false],
    [false, false, 2, true, true, true, true, true, true, true, true, 2, false, false],
    [false, false, 2, true, true, true, true, true, true, true, true, 2, false, false],
    [false, false, 2, true, true, true, true, true, true, true, true, 2, false, false],
    [false, false, 2, true, true, true, true, true, true, true, true, 2, false, false],
    [2, 2, 2, true, true, true, true, true, true, true, true, 2, 2, 2],
    [2, true, true, true, true, true, true, true, true, true, true, true, true, 2],
    [2, true, true, true, true, true, true, true, true, true, true, true, true, 2],
    [2, true, true, true, true, true, true, true, true, true, true, true, true, 2],
    [2, true, true, true, true, true, true, true, true, true, true, true, true, 2],
    [2, 2, 2, true, true, true, true, true, true, true, true, 2, 2, 2],
  ],
];
