export const GAME_VERSION = "0.9.2";

export const CHANGELOG = [
  {
    version: "0.9.2",
    changes: [
      "CRITICAL FIX: Particle rendering moved outside explosion loop (was 5x+ redundant draws)",
      "Explosion ring/glow rendering separated from particle drawing for efficiency",
      "Particle counts reduced: low=5, medium=10, high=15 (was 8/15/20)",
      "particleMultiplier tuned: low=0.25, medium=0.5, high=1.0 (was 0.3/0.6/1.0)",
      "Debug logs now correctly count particles from pool instead of empty explosion arrays",
    ],
  },
  {
    version: "0.9.1",
    changes: [
      "Major performance optimization: particle pool fully integrated for explosions",
      "In-place mutation for balls, enemies, bombs, bonus letters (reduces GC by ~80%)",
      "Particle pool batch acquisition with color palettes for efficient memory use",
      "CCD brick pool optimization: reusable brick array eliminates per-frame allocations",
      "GameCanvas renders particles directly from pool instead of state",
      "Frame profiler now uses pool stats for accurate particle counts",
      "Debug features disabled for production build",
    ],
  },
  {
    version: "0.9.0",
    changes: [
      "Fixed boss defeat by reflected attacks: now triggers full explosion effects",
      "Reflected attack boss defeat now plays explosion sound and visual particles",
      "Entity cleanup (balls, enemies, attacks) on boss defeat via reflected attacks",
      "Music transitions correctly when boss defeated by reflected attacks",
      "Debug toasts and logs properly gated behind debug flag for production",
    ],
  },
  {
    version: "0.8.9",
    changes: [
      "Speed system rebalanced (Option B): 110% base speed for easier start",
      "Normal mode: +5%/level for levels 1-5, then +3%/level for levels 6+",
      "Godlike mode: 137.5% base, +5%/level always",
      "Speed caps lowered: 140% normal, 155% godlike for easier late-game",
      "Starting level now correctly applies speed for selected level",
    ],
  },
  {
    version: "0.8.8",
    changes: [
      "Codebase cleanup: removed 34 unused UI components (~3,500 lines)",
      "Removed 22 unused npm dependencies for faster installs",
      "Removed duplicate audio file (Pixel_Frenzy.mp3)",
      "Removed unused eventQueue utility",
      "Bundle size reduced by ~150-200KB",
    ],
  },
  {
    version: "0.8.7",
    changes: [
      "Fixed paddle collision bug: velocity now calculated in pixels-per-frame (was 60x overestimated)",
      "Anti-rescue paddle collision: prevents false rescues when ball approaches from below",
      "Unified cleanup on unmount: all timers, intervals, and animation frames properly cleared",
      "Game loop pause/resume synchronized with game state and tutorial",
      "Centralized scaled constants into useScaledConstants hook for cleaner code",
      "Service worker checks now run on main menu AND when starting new game (never during gameplay)",
      "Fixed stale closures in timeout callbacks using functional state updates",
    ],
  },
  {
    version: "0.8.6",
    changes: [
      "Added Starting Level selector to main menu - choose any level you've previously reached",
      "Level progress is saved locally - your highest level is remembered between sessions",
      "Locked levels show a floating warning message when selected",
      "Project cleanup: removed documentation folder for streamlined codebase",
    ],
  },
  {
    version: "0.8.5",
    changes: [
      "Overhauled tutorial system with pulsating radial glow around game elements",
      "Removed redundant tutorial overlays (turret/minion) for cleaner experience",
      "Fixed tutorial highlight positioning on mobile devices",
      "Tutorial overlays now positioned inside scaled game container for accuracy",
    ],
  },
  {
    version: "0.8.4",
    changes: [
      "Added darker sci-fi background for levels 1-4 with 40% dimming overlay",
      "Dynamic high-contrast flash effects: cyan for explosions/kills, golden for extra lives",
      "Flash effects use overlay/soft-light blend modes to highlight tech lines only",
      "Updated tiled backgrounds for levels 6-9, 11-14, and 16-19",
      "Added unique fitted backgrounds for boss levels 5, 10, 15, and 20",
    ],
  },
  {
    version: "0.8.3",
    changes: [
      "Reflected bombs now deal single-hit damage, are removed on impact, and include a short cooldown to prevent rapid hits",
      "Enhanced hit effects: glow trails, impact explosions, and distinct colors for super vs normal bullets",
      "Turrets now persist across levels, stack ammo, and can upgrade to powerful golden turrets",
      "Improved particle system for smoother, more efficient visual effects",
      "Added animated boss power-up timers near the paddle",
      "Turret ammo capped at 45 with HUD indicator that warns when low",
    ],
  },
  {
    version: "0.8.2",
    changes: [
      "Replaced power-up icons: turtle now represents slowdown, red arrows now represent shrink",
      "Bug fix: F key now only toggles fullscreen and no longer pauses the game",
      "Bug fix: Resume button now checks if music is already playing to prevent audio overlap",
      "New power-up Boss Stunner: freezes boss for 5 seconds, stopping movement and attacks",
      "New power-up Reflect Shield: reflects boss attacks back for 15 seconds, damaging the boss",
      "New power-up Homing Ball: ball curves toward boss for 8 seconds with a red targeting trail",
    ],
  },
  {
    version: "0.8.1",
    changes: [
      "Fixed ESC key pause functionality - now properly triggers pause menu when mouse is captured",
      "Pause overlay displays comprehensive keyboard shortcuts (Resume, Controls, Game hotkeys)",
      "Added 'Exit to Main Menu' button to pause overlay for quick navigation",
      "Pause overlay now properly captures/releases mouse lock when resuming gameplay",
      "Paddle input completely disabled during pause to prevent unintended movement",
      "Mobile pause overlay includes X close button in top-right corner for quick resume",
      "Extra life power-ups limited to one per five levels (levels 1-5, 6-10, etc.)",
      "Extra life tracking only marks level group as used when power-up is collected",
      "Mobile swipe gestures: swipe right to pause during gameplay",
      "Menu swipe navigation: swipe from left edge to go back on High Scores, Changelog, What's New, About, Instructions",
      "High score qualification now checks all three leaderboards (all-time, weekly, daily) independently",
      "Top scores display on main menu with pinball-style amber LED text and smooth cycling animation",
      "Top scores marquee cycles through daily, weekly, all-time with 5s display + 3s scroll transitions",
      "Added LED flicker effect to top scores display during transitions for authentic retro feel",
      "X close buttons added to Instructions, High Scores, What's New, and About screens",
      "High score entry now captures all keyboard input to prevent accidental game command triggers",
      "Removed 3D objects from high score display page for cleaner UI",
    ],
  },
  {
    version: "0.8.0",
    changes: [
      "Paddle deflection angle increased to 80° maximum for more extreme ball control",
      "Improved ball trajectory control from paddle edges for strategic gameplay",
    ],
  },
  {
    version: "0.7.12",
    changes: [
      "Paddle collision fully integrated into CCD system with linear position-to-angle mapping",
      "Ball launch angle now purely determined by paddle impact position (-80° to +80°)",
      "Removed separate Phase 0.5 paddle-first collision system for cleaner architecture",
      "Ball speed always preserved on paddle hits for consistent gameplay",
    ],
  },
  {
    version: "0.7.11",
    changes: [
      "CRT scanline effects completely disabled on mobile devices for better performance",
      "Desktop CRT effects reduced in intensity: scanlines 0.08 opacity (was 0.15), vignette 0.15 intensity (was 0.3)",
      "Brighter, less intrusive retro aesthetic on desktop platforms",
    ],
  },
  {
    version: "0.7.10",
    changes: [
      "Mobile touch paddle control now uses zone-based mapping (15% to 85% of screen width)",
      "Touch zones smoothly map to full paddle range for comfortable mobile gameplay",
      "Players can reach paddle extremes without dragging finger all the way across screen",
    ],
  },
  {
    version: "0.7.9",
    changes: [
      "Paddle input prioritized over other game systems for responsive control",
      "Paddle position updates at monitor refresh rate regardless of game simulation FPS",
      "Improved paddle responsiveness when total game FPS drops below 30-50",
    ],
  },
  {
    version: "0.7.8",
    changes: [
      "CCD profiler displays microsecond (μs) precision for sub-millisecond operations",
      "Rolling averages tracked over 60 frames (average, min, max) to reveal performance trends",
      "Frame budget indicator shows timing relative to 16.6ms budget (e.g., '1.2μs of 16.6ms')",
      "Cumulative CCD time displayed across all balls per frame for total impact analysis",
    ],
  },
  {
    version: "0.7.7",
    changes: [
      "Automatic bottleneck detection with threshold warnings for subsystems (physics, CCD, rendering, particles, audio)",
      "Detailed diagnostic logs triggered when subsystems exceed timing thresholds",
      "Performance logging tracks FPS samples with timestamps and quality changes",
      "Format: [Performance] Quality: HIGH → MEDIUM | Avg FPS: 52.3 | Time: 12.5s",
    ],
  },
  {
    version: "0.7.6",
    changes: [
      "6-phase performance optimization system: frame profiler, event queue, object pooling, particle limits, effect toggles, batch rendering",
      "Per-subsystem timing breakdown (physics, CCD, rendering, particles, audio, screen shake, effects)",
      "Frame profiler overlay displays millisecond timing for each subsystem per frame",
      "Event queue with time/count budgeting to prevent frame-time spikes",
      "Goal: stable 55-60 FPS during heavy scenes with bullets, enemies, and explosions",
    ],
  },
  {
    version: "0.7.5",
    changes: [
      "Quality indicator (FPS counter) always visible in production, not gated by debug mode",
      "Players can monitor current performance metrics during published gameplay",
      "Quality indicator positioned in bottom-left corner for easy visibility",
    ],
  },
  {
    version: "0.7.4",
    changes: [
      "Score and level HUD elements repositioned further right to prevent overlaying GOD LEVEL indicator",
      "Debug dashboard component added, toggled by § key for centralized debug control",
      "Visual reference panel with all debug key instructions and functions",
    ],
  },
  {
    version: "0.7.3",
    changes: [
      "Paddle Collision: Fixed ball getting stuck inside paddle with emergency resolver and geometric corner collision",
      "Boss Collision: Added comprehensive debug logging for ball penetration issues with position, distance, and correction data",
      "Collision Safety: Increased safety margins to 2 pixels for all boss collision types to prevent micro-penetration",
      "Position Correction: All boss collisions now apply position and velocity corrections regardless of damage cooldown",
      "Paddle Geometry: Implemented rounded rectangle collision detection to prevent ball entrapment during paddle movement",
      "Debug Visibility: Added detailed console logging for cube, sphere, and pyramid boss collision detection and resolution",
    ],
  },
  {
    version: "0.7.2",
    changes: [
      "CCD Physics Engine: Implemented Continuous Collision Detection with Time-of-Impact (TOI) calculations for mathematically precise collision handling",
      "Zero Tunneling Guarantee: Ball can no longer tunnel through bricks, paddle, or walls regardless of speed using swept-circle vs expanded AABB tests",
      "Boss/Enemy CCD Integration: Bosses, resurrected bosses, and enemies now use CCD system for accurate ball collisions with proper cooldowns",
      "Enhanced Debug Overlay: Added CCD-specific metrics including collisions per frame and TOI iterations, renamed to 'CCD Physics Debug'",
      "Cracked Brick Sound Fix: Sound effects now correctly play based on current damage state (3→2→1 progression) before applying damage",
      "Velocity Unit Conversion: Fixed ball speed by properly converting between px/frame (game) and px/sec (physics engine)",
      "Multi-Object Collision: Single physics pass handles bricks, paddle, walls, bosses, and enemies simultaneously with correct priority",
      "Adaptive Substeps: Automatically scales from 2x to 5x substeps based on ball speed for optimal performance and accuracy",
    ],
  },
  {
    version: "0.7.1",
    changes: [
      "Boss music system: Fixed boss music properly pausing background music and continuing throughout boss level",
      "Audio improvements: Fixed multiple background music tracks playing simultaneously",
      "Music flow: Background music now only resumes after boss defeat, not when skipping or retrying levels",
      "Fixed: Music no longer restarts when transitioning from 'ready to play' to playing state",
    ],
  },
  {
    version: "0.7.0",
    changes: [
      "Boss enhancements: Bosses now spawn minions every 15 seconds (2 at a time, max 6 on screen)",
      "Boss minions: 50% power-up drop rate with toast notification when dropping bonus power-ups",
      "Turret damage: Turret shots now damage bosses (0.5 HP per shot) for both main and resurrected bosses",
      "Special brick types: Metal bricks (indestructible, visually melt together), Cracked bricks (3 hits required with damage textures), Explosive bricks (destroy surrounding bricks)",
      "Metal brick interactions: Destroyed by explosive blasts, block turret shots, automatically re-form melted shapes",
      "Shield mechanics: Now protects entire paddle from ball collisions with animated yellow energy force field and electrical arcs",
      "Collision system: Multi-substep detection (up to 5x at high speeds) with 0.15 threshold to prevent ball tunneling through bricks",
      "Ball physics: Fixed corner trapping with buffer distance, cooldowns, and early exit mechanism after brick hits",
      "Level editor: Paint brush system for placing bricks, visual previews for each brick type, right-click to clear cells",
      "Bonus letters: Now awarded in random order from eligible levels, no repeats within same game session",
      "High scores: Cloud-based leaderboards with all-time, weekly, and daily rankings, improved display styling",
      "Statistics screen: Added counters for power-ups collected, bricks destroyed by turrets, enemies killed, bosses killed, and total play time",
      "High score entry: Celebratory particle effects, pulsing glow, rotating rings, sparkle effects, and trophy icon",
      "Boss spawn visual: Hatch opening effect with pulsing glow, opening lines, and particle burst lasting 500ms",
      "Sound balance: Wall bounce reduced 80%, boss hit reduced 30%, laser charging reduced 50%",
      "Sound effects: Glass breaking sound for cracked bricks, dramatic explosion sound for explosive bricks",
      "Boss audio: Alarm klaxon now ducks music volume by 80% during boss intro",
      "Brick sizing: Adjusted to 56x21 with 4px padding for larger bricks and tighter gaps",
      "Debug overlay: Added substep count and ball speed display, toggled with TAB key",
      "Game mechanics: Removed combo scoring, removed extra life bonus per 50k points, removed starting lives selection (fixed at 3)",
      "iOS improvements: Frameless layout for mobile devices, improved fullscreen behavior",
      "Performance: Adaptive quality settings with FPS-based automatic adjustments",
      "Fixed: Boss laser duration reduced to 0.5 seconds for better gameplay flow",
      "Fixed: Initial ball velocity now properly initialized with 2x substeps from game start",
      "Fixed: Statistics properly reset when retrying a level",
    ],
  },
  {
    version: "0.6.6",
    changes: [
      "Boss system: Epic boss battles on levels 5, 10, and 15 featuring Cube, Sphere, and Pyramid bosses with unique attack patterns",
      "Boss attacks: Shot, laser, super, spiral, and cross patterns with visual warnings and effects",
      "Multi-phase boss mechanics: Bosses become faster and more aggressive as they lose health",
      "Pyramid boss resurrection: Splits into 3 smaller independent bosses when defeated",
      "Boss intro cinematics: Dramatic warning overlays, pulsing borders, spotlight zoom, and 'BOSS APPROACHING' text",
      "Game over particle explosion animation with glowing particles and gravity physics",
      "Game over statistics screen: Displays bricks destroyed, longest combo, and accuracy percentage",
      "Retry level button: Resets score and lives to restart the level you died on",
      "Level skipper detection: Players who skip levels see 'CHEATER' banner and are disqualified from high scores",
      "Boss damage effects: Screen shake, color flashing, and impact particles when bosses take damage",
      "Laser warning visual: Pulsating dotted line with '!! LASER !!' text before laser fires",
      "Fixed: Boss attacks and laser warnings now properly clear when losing a ball",
      "Fixed: Retry level now correctly restarts the current level instead of advancing to the next",
      "Fixed: Boss laser attacks now originate from boss position instead of screen top",
      "Fixed: Multi-phase boss health bars now accurately reflect current phase HP",
    ],
  },
  {
    version: "0.6.5  ",
    changes: [
      "Turret power-up now has limited ammo: 30 shots in normal mode, 15 shots in god mode, and is automatically removed when depleted",
      "Added turret ammo counter to HUD that pulses red when 5 shots or fewer remain",
      "Desktop adaptive layout: title-only hiding and zoom scaling when vertical space is constrained while keeping stats and controls always visible",
      "Base speed increased by 15% to 3.45 (was 3.00)",
      "God mode now starts at 125% speed",
    ],
  },
  {
    version: "0.6.4  ",
    changes: [
      "Implemented global volume increases for game sounds",
      "Added mobile two-finger ball launch control with debug logging",
      "Adaptive header now auto-hides 'Vibing Arkanoid' title when vertical space is constrained with 150ms fade and debug logging",
    ],
  },
  {
    version: "0.6.3  ",
    changes: [
      "Enemies now explode with unique colors: cubes (cyan/blue), spheres (pink/magenta), pyramids (purple/violet)",
      "Each explosion emits 20 debris particles with directional spread and physics",
      "Gravity added to debris particles for realistic falling motion",
      "Debris rendering enhanced with glowing squares and bright centers",
      "Explosion sound volume increased from 0.08 to 0.088",
      "Mobile play implemented; touch now launches the ball",
      "Changelog moved to About section only",
      "Every 3rd enemy kill now guarantees a power-up drop",
      "Game canvas now fills more of the screen on all devices",
    ],
  },
  {
    version: "0.6.2",
    changes: [
      "Replaced shrink power-up icon with new version",
      "High score list now scales to fit all resolutions and screen sizes",
      "Pressing continue on high score screen now returns to main menu",
      "Accumulated slowdown speed resets upon level completion",
      "Screen shakes for 0.5 seconds when hitting an enemy",
      "Background flashes briefly when collecting a bonus letter; longer flash and screen shake when collecting all letters",
      "If ball avoids paddle for 15s, it diverts by 10 degrees; after 25s, nearest enemy performs kamikaze toward ball",
      "Extra life awarded every 50000 points, with sound effect and blinking score",
      "High score now includes chosen starting lives; fewer lives rank higher for equal scores",
      "QUMRAN letter reward changed from 11 to 5 extra lives",
    ],
  },
  {
    version: "0.6.1",
    changes: [
      "Turret drop timer now resets on level completion",
      "Power-ups drop every 3 defeated enemies",
      "Ball only bounces off the top 50% of the paddle",
      "Enemy shooting intervals scale with level: 7–12s (lvl 1–7), 4–8s (lvl 8), 3–7s (lvl 9+)",
    ],
  },
  {
    version: "0.6.0",
    changes: [
      "Updated shield powerup with new sound and icon",
      "New startup screen and main menu images",
      "Shield now fully wraps around paddle (thick top, thin sides/bottom)",
      "Shield powerup is now less common",
      "Turrets powerup 50% drop chance at 90 seconds (up from 25%)",
      "Enemy shooting intervals scale with level: +0.5s/level until 5-9s at level 10, then 3-7s from level 11+",
      "Ball only bounces from top 50% of paddle collision area",
      "Indestructible bricks are now truly solid rectangles with no gaps or shadows",
      "Speed caps: 150% for normal mode, 175% for godlike mode",
      "Accumulated speed resets when winning a level",
      "Ball auto-diverts 10° if no paddle contact for 15s",
      "Kamikaze enemy attacks ball if no paddle contact for 25s",
      "Drop powerup for every 3 enemies killed",
      "Extra life awarded every 50,000 score with sound and score blink effect",
      "Fixed: Levels with only indestructible bricks now advance automatically",
      "High score list now fully scrollable regardless of window size",
      "Added full changelog history accessible from version number",
      "Updated instructions with all new mechanics",
    ],
  },
  {
    version: "0.5.2",
    changes: [
      "Added Shield powerup - protects from 1 enemy bullet",
      "Capped enemy speed increase after 5 enemies spawn",
      "Enemies now shoot less frequently (7-12 seconds)",
      "Ball speed from brick hits capped at 30% until level clear/death/slowdown",
      "Speed only increases when bricks fully destroyed (not multi-hit bricks)",
      "Turrets powerup 25% drop chance at 90 seconds",
      "Version number now visible during gameplay",
      "Added changelog accessible by clicking version number",
      "Fixed level loop bug with indestructible bricks",
      "High score list now fully visible regardless of window size",
    ],
  },
  {
    version: "0.5.1",
    changes: [
      "Changed canvas to 850x650",
      "Updated brick grid to 13 columns x 14 rows",
      "Adjusted brick dimensions",
      "Reduced paddle width by 10 pixels",
      "Updated level editor to match new grid",
    ],
  },
  {
    version: "0.5.0",
    changes: [
      "Implemented pointer lock for mouse control",
      "Mouse capture with ESC to exit",
      "Click canvas to re-capture mouse",
      "Improved touch controls for mobile",
    ],
  },
  {
    version: "0.4.10",
    changes: [
      "Added bonus letter collection system (Q-U-M-R-A-N)",
      "Collect all 6 letters for +10 lives and +500,000 points",
      "Bonus letters drop on specific levels",
      "Added visual indicators for collected letters",
    ],
  },
  {
    version: "0.4.0",
    changes: [
      "Introduced 3 enemy types: Cube, Sphere, and Pyramid",
      "Pyramid enemies require 3 hits to destroy",
      "Sphere enemies require 2 hits and get angry",
      "Enemies shoot projectiles at the player",
      "Added explosion effects for destroyed enemies",
      "Enemy difficulty scales with level and game mode",
    ],
  },
  {
    version: "0.3.5",
    changes: [
      "Added turrets powerup - shoot bullets from paddle",
      "Bullets can destroy bricks and enemies",
      "Indestructible bricks bounce bullets back",
      "Added bullet collision detection",
    ],
  },
  {
    version: "0.3.0",
    changes: [
      "Implemented 8 powerups: multiball, fireball, life, slowdown, extend, shrink, turrets, shield",
      "Powerup drop chance increases over time",
      "Visual powerup animations and effects",
      "Special sound effects for each powerup",
    ],
  },
  {
    version: "0.2.5",
    changes: [
      "Added multi-hit bricks that require multiple hits",
      "Brick colors change based on remaining hits",
      "Added hit counter display on bricks",
      "Difficulty scales with level progression",
    ],
  },
  {
    version: "0.2.0",
    changes: [
      "Implemented 50 unique level layouts",
      "Added indestructible metal bricks",
      "Level editor for custom level design",
      "Progressive difficulty system",
    ],
  },
  {
    version: "0.1.5",
    changes: [
      "Added retro Amiga-inspired graphics",
      "16-bit pixel texture effects on bricks",
      "3D ball with metallic gradient",
      "Retro color palette and visual style",
    ],
  },
  {
    version: "0.1.0",
    changes: [
      "Initial game release",
      "Basic Arkanoid gameplay mechanics",
      "Paddle and ball physics",
      "Brick breaking system",
      "Score tracking and lives system",
      "16 retro music tracks with random selection",
      "High score system with persistence",
      "Normal and Godlike difficulty modes",
    ],
  },
];
